---
# go service
apiVersion: v1
kind: Service
metadata:
  name: go
  labels:
    app: go
spec:
  type: LoadBalancer
  ports:
    - port: 8484
  selector:
    app: go
---
# go deployment with two go pod with go app container
apiVersion: apps/v1
kind: Deployment
metadata:
  name: go
  labels:
    app: go
spec:
  replicas: 2
  selector:
    matchLabels:
      app: go
  template:
    metadata:
      labels:
        app: go
    spec:
      containers:
      - image: chiju/go:kubernetes_nginxfrontend
        name: go
        ports:
        - containerPort: 8484
